openapi: "3.0.0"
info:
    title: Doctor Search API
    description: Get information about doctors, cities, and specialties with the Doctor Search API.
    version: 0.0.3
servers:
    - url: https://api.doctorsearch.me
paths:
    /doctors:
        get:
            description: Returns doctors with optional filters.
            tags:
                - Doctors
            operationId: findDoctors
            parameters:
                - name: name
                  in: query
                  description: Name of the doctor.
                  required: false
                  schema:
                    type: string
                    example: John Smith
                - name: city
                  in: query
                  description: City that the doctor is in.
                  required: false
                  schema:
                    type: string
                    example: Austin
                - name: state
                  in: query
                  description: State that the doctor is in.
                  required: false
                  schema:
                    type: string
                    example: Texas
                - name: phone
                  in: query
                  description: Phone number of the doctor.
                  required: false
                  schema:
                    type: string
                    example: 111-222-3333
                - name: specialty
                  in: query
                  description: Speciality that the doctor practices.
                  required: false
                  schema:
                    type: string
                    example: Dermatology
                - name: limit
                  in: query
                  description: Maximum number of results to return.
                  required: false
                  schema:
                    type: integer
                    format: int32
                    minimum: 1
                    maximum: 100
                    default: 20
                    example: 10
            responses:
                200:
                    description: Successful response for Doctors
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Doctor'
                404:
                    description: Not found response
                    content:
                        text/plain:
                            schema:
                                title: Doctors not found
                                type: string
                                example: Not found
    /doctors/{id}:
        get:
            description: Returns a doctor based on a single ID.
            tags:
                - Doctors
            operationId: findDoctorById
            parameters:
                - name: id
                  in: path
                  description: ID of the doctor to get.
                  required: true
                  schema:
                    type: integer
                    format: int64
                    example: 1434
            responses:
                200:
                    description: Successful response for Doctor
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Doctor'
                404:
                    description: Not found response
                    content:
                        text/plain:
                            schema:
                                title: Doctor not found
                                type: string
                                example: Not found
    /cities:
        get:
            description: Returns cities with optional filters.
            tags:
                - Cities
            operationId: findCities
            parameters:
                - name: name
                  in: query
                  description: Name of the city.
                  required: false
                  schema:
                    type: string
                    example: Austin
                - name: state
                  in: query
                  description: State that the city is in.
                  required: false
                  schema:
                    type: string
                    example: Texas
                - name: county
                  in: query
                  description: County that the city is in.
                  required: false
                  schema:
                    type: string
                    example: Travis
                - name: zip
                  in: query
                  description: ZIP Code of the city.
                  required: false
                  schema:
                    type: integer
                    format: int32
                    example: 78705
                - name: minPopulation
                  in: query
                  description: Minimum population of the cities that will be returned.
                  required: false
                  schema:
                    type: integer
                    format: int32
                    minimum: 0
                    example: 50000
                - name: maxPopulation
                  in: query
                  description: Maximum population of the cities that will be returned.
                  required: false
                  schema:
                    type: integer
                    format: int32
                    minimum: 0
                    example: 5000000
                - name: limit
                  in: query
                  description: Maximum number of results to return.
                  required: false
                  schema:
                    type: integer
                    format: int32
                    minimum: 1
                    maximum: 100
                    default: 20
                    example: 10
            responses:
                200:
                    description: Successful response for Cities
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/City'
                404:
                    description: Not found response
                    content:
                        text/plain:
                            schema:
                                title: Cities not found
                                type: string
                                example: Not found
    /cities/{id}:
        get:
            description: Returns a city based on a single ID.
            tags:
                - Cities
            operationId: findCityById
            parameters:
                - name: id
                  in: path
                  description: ID of the city to get.
                  required: true
                  schema:
                    type: integer
                    format: int64
                    example: 15
            responses:
                200:
                    description: Successful response for City
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/City'
                404:
                    description: Not found response
                    content:
                        text/plain:
                            schema:
                                title: City not found
                                type: string
                                example: Not found
    /specialties:
        get:
            description: Returns specialties with optional filters.
            tags:
                - Specialties
            operationId: findSpecialties
            parameters:
                - name: name
                  in: query
                  description: Name of the specialty.
                  required: false
                  schema:
                    type: string
                    example: Dermatology
                - name: city
                  in: query
                  description: City that the specialty is practiced in.
                  required: false
                  schema:
                    type: string
                    example: Austin
                - name: doctor
                  in: query
                  description: Doctor that practices the specialty.
                  required: false
                  schema:
                    type: string
                    example: John Smith
                - name: category
                  in: query
                  description: Category of the specialty.
                  required: false
                  schema:
                    type: string
                - name: description
                  in: query
                  description: Description of the specialty.
                  required: false
                  schema:
                    type: string
                - name: limit
                  in: query
                  description: Maximum number of results to return.
                  required: false
                  schema:
                    type: integer
                    format: int32
                    minimum: 1
                    maximum: 100
                    default: 20
                    example: 10
            responses:
                200:
                    description: Successful response for Specialties
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Specialty'
                404:
                    description: Not found response
                    content:
                        text/plain:
                            schema:
                                title: Specialties not found
                                type: string
                                example: Not found
    /specialties/{id}:
        get:
            description: Returns a specialty based on a single ID.
            tags:
                - Specialties
            operationId: findSpecialtyById
            parameters:
                - name: id
                  in: path
                  description: ID of the specialty to get.
                  required: true
                  schema:
                    type: integer
                    format: int64
                    example: 5
            responses:
                200:
                    description: Successful response for Specialty
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Specialty'
                404:
                    description: Not found response
                    content:
                        text/plain:
                            schema:
                                title: Specialty not found
                                type: string
                                example: Not found
tags:
    - name: Doctors
      description: Get information about doctors.
    - name: Cities
      description: Get information about cities.
    - name: Specialties
      description: Get information about specialties.
components:
    schemas:
        Doctor:
            title: Doctor
            type: object
            required:
                - id
                - name
                - city
                - cityId
                - state
                - phone
                - specialty
                - specialtyId
                - biography
                - image
            properties:
                id:
                    type: integer
                    description: ID that uniquely identifies the doctor.
                    format: int64
                    example: 1434
                name:
                    type: string
                    description: Name of the doctor.
                    example: John Smith
                city:
                    type: string
                    description: City that the doctor is in.
                    example: Austin
                cityId:
                    type: integer
                    description: ID of the City object of the doctor's city.
                    format: int64
                    example: 15
                state:
                    type: string
                    description: State that the doctor is in.
                    example: Texas
                phone:
                    type: string
                    description: Phone number of the doctor.
                    example: 111-222-3333
                specialty:
                    type: string
                    description: Specialty that the doctor practices.
                    example: Dermatology
                specialtyId:
                    type: integer
                    description: ID of the Specialty object of the doctor's specialty.
                    format: int64
                    example: 5
                biography:
                    type: string
                    description: Biography of the doctor.
                    example: John Smith went to UT Southwestern and became a dermatologist afterwards.
                image:
                    type: string
                    description: URL of an image of the doctor.
                    example: https://www.exampleimages.com/johnsmith.jpg
        City:
            title: City
            type: object
            required:
                - id
                - name
                - description
                - state
                - county
                - zip
                - population
                - doctors
                - doctorIds
                - specialties
                - specialtyIds
                - image
            properties:
                id:
                    type: integer
                    description: ID that uniquely identifies the city.
                    format: int64
                    example: 15
                name:
                    type: string
                    description: Name of the city.
                    example: Austin
                description:
                    type: string
                    description: Description of the city.
                    example: Austin is the capital of Texas.
                state:
                    type: string
                    description: State that the city is in.
                    example: Texas
                county:
                    type: string
                    description: County that the city is in.
                    example: Travis
                zip:
                    type: integer
                    description: ZIP Code of the city.
                    format: int32
                    example: 78705
                population:
                    type: integer
                    description: Population of the city.
                    format: int32
                    example: 950715
                doctors:
                    type: array
                    description: Names of doctors in the city.
                    items:
                        type: string
                        example: John Smith
                doctorIds:
                    type: array
                    description: Doctor object IDs of doctors in the city.
                    items:
                        type: integer
                        format: int64
                        example: 1434
                specialties:
                    type: array
                    description: Names of specialties that are practiced in the city.
                    items:
                        type: string
                        example: Dermatology
                specialtyIds:
                    type: array
                    description: Specialty object IDs of specialties that are practiced in the city.
                    items:
                        type: integer
                        format: int64
                        example: 5
                image:
                    type: string
                    description: URL of an image of the city.
                    example: https://www.exampleimages.com/austin.jpg
        Specialty:
            title: Specialty
            type: object
            required:
                - id
                - name
                - category
                - description
                - doctors
                - doctorIds
                - cities
                - cityIds
                - image
            properties:
                id:
                    type: integer
                    description: ID that uniquely identifies the specialty.
                    format: int64
                    example: 5
                name:
                    type: string
                    description: Name of the specialty.
                    example: Dermatology
                category:
                    type: string
                    description: Category of the specialty.
                description:
                    type: string
                    description: Description of the specialty.
                doctors:
                    type: array
                    description: Names of doctors that practice the specialty.
                    items:
                        type: string
                        example: John Smith
                doctorIds:
                    type: array
                    description: Doctor object IDs of doctors that practice the specialty.
                    items:
                        type: integer
                        format: int64
                        example: 1434
                cities:
                    type: array
                    description: Names of cities that have doctors practicing the specialty.
                    items:
                        type: string
                        example: Austin
                cityIds:
                    type: array
                    description: City object IDs of cities that have doctors practicing the specialty.
                    items:
                        type: integer
                        format: int64
                        example: 15
                image:
                    type: string
                    description: URL of an image of the specialty.
                    example: https://www.exampleimages.com/dermatology.jpg